### PR TITLE
Add code-block and chart

### PR DESCRIPTION
**Pull request by Winterspringkle**
image
image
Please fill the code block with demo. @git-hulk

### CODE REVIEW

**Comment by PragmaTwice** [comment]
The CI failed. Could you take a look to it? Seems the lockfile is modified unexpectedly.

**Comment by Winterspringkle** [comment]
@PragmaTwice  Antd, E-charts and ACE-coder are added in package list. The yarn.lock is updated in this version.

**Comment by PragmaTwice** [comment]
@git-hulk Is there any client code for demonstration in the website?

**Comment by PragmaTwice** [comment]
BTW the CI still failed due to the lockfile issue.

**Comment by git-hulk** [comment]
> @git-hulk Is there any client code for demonstration in the website?

I can add those client demos today.

**Comment by git-hulk** [comment]
@Winterspringkle Can use below client code samples:

Java:

```java
package org.example;
import redis.clients.jedis.Jedis;
import redis.clients.jedis.JedisPool;

JedisPool pool = new JedisPool("127.0.0.1", 6666);

try (Jedis jedis = pool.getResource()) {
	jedis.set("username", "kvrocks");
  System.out.println(jedis.get("username"));
}
```

Go

```go
import (
	"context"
	"fmt"
	"github.com/redis/go-redis/v9"
)

client := redis.NewClient(&redis.Options{
	Addr:	  "localhost:6666",
})

err := client.Set(ctx, "username", "kvrocks", 0).Err()
if err != nil {
    panic(err)
}

val, err := client.Get(ctx, "username").Result()
if err != nil {
    panic(err)
}
fmt.Println("username", val)
```

Python

```python
r = redis.Redis(host='localhost', port=6666, decode_responses=True)

r.set('username', 'kvrocks')
# True
r.get('username')
# kvrocks
```

**Comment by PragmaTwice** [comment]
I think you can try the command in your local, and push the code after the yarn install command successfully executed.

**Comment by Winterspringkle** [comment]
@PragmaTwice Sorry for previous centralized submission.s This time the CI error is solved in local environment.
image

**Comment by Winterspringkle** [comment]
I will check build error latter.

**Comment by Winterspringkle** [comment]
@PragmaTwice All checks have passed and please check the effect of code block and charts.

**Comment by git-hulk** [comment]
> @git-hulk Could you confirm the redis command coverage rate in the pie chart?

Sure, the Redis commands may be added or deleted in different versions, so I think it makes no sense to calculate the percentage of supported commands. How about the supported data structures(not including the Redis module) and core features like Lua/Transaction? 


If yes, Redis Core supports String/Hash/ZSet/List/Set/HyperLogLog/Lua/Transaction, and Kvrocks now supports String/Hash/ZSet/List/Set/Lua/Transaction, so we can say the supported features is 

88.5%, and 12.5% are doing.

**Comment by Winterspringkle** [comment]
Of cource, I will modify the data according to suggested change.

**Comment by PragmaTwice** [comment]
Thanks for your contribution!

**Pull request merged**
