### PR TITLE
introduce docusaurus framework

### PR DESCRIPTION
**Pull request by tisonkun**
You can checkout and run at local with `yarn start`.

### CODE REVIEW

**Comment by tisonkun** [comment]
@git-hulk the logo svg and favicon isn't quite good-look, though. I'm unfamiliar with draw a logo and maybe you can help on creating a better version.

**Comment by tisonkun** [comment]
image

Note that the favicon has been around with white background, and the navbar logo is a bit small.

**Comment by git-hulk** [comment]
I tried it on my side, looks really great to me.
image

**Review by git-hulk — APPROVED** [review]

**Comment by git-hulk** [comment]
> @git-hulk the logo svg and favicon isn't quite good-look, though. I'm unfamiliar with draw a logo and maybe you can help on creating a better version.

OK, I'm also unfamiliar with that. Will contact the original designer to help.

**Comment by tisonkun** [comment]
@git-hulk thanks for your review. I'll do some random manual test and merge this PR later.

**Comment by tisonkun** [comment]
> OK, I'm also unfamiliar with that. Will contact the original designer to help.

SGTM. It can be a follow-up later. Looking forward to see the original designer come back to the community :)

**Comment by git-hulk** [comment]
https://github.com/tianlingyu1997 is the original designer, but seems he/she's NOT active in GitHub. I'll try to contact he/she offline, hope it won't block this PR.

**Comment by tisonkun** [comment]
> hope it won't block this PR.

@git-hulk I'm going to merge this PR now. Logo issue should not be a blocker - we can improve it later.

**Comment by git-hulk** [comment]
copy that

**Comment by tisonkun** [comment]
@git-hulk you're welcome. Now it's clear (to me, at least) to add new pages (user document, dev document, community infos, blogs) under the corresponding category. I'm going to move existing contents from blogs and wikis to our website in the next weeks.

**Comment by git-hulk** [comment]
OK, agreed. Maybe I can help on this part.

**Pull request merged**
