### PR TITLE
Add the committers page in community

### PR DESCRIPTION
**Pull request by git-hulk**
image

### CODE REVIEW

**Review by PragmaTwice — APPROVED** [review]

**Review by tisonkun — APPROVED** [review]
Better than nothing. But I'm curious how we keep the information up-to-date.

**Comment by PragmaTwice** [comment]
I did not know `https://github.com/<username>.png` will be a valid image before. That is interesting.

**Comment by git-hulk** [comment]
> Better than nothing. But I'm curious how we keep the information up-to-date.

My rough thought is to update the information manually as soon as possible. Of course, it'd be better if it's possible to automate this with the voting process.

**Comment by git-hulk** [comment]
> I did not know `https://github.com/<username>.png` will be a valid image before. That is interesting.

Yes, I also learned this from other projects.

**Pull request merged**
